#!/usr/bin/env bash
#
# Cloud Agent install step for the GoLo marketing site.
#
# Idempotent repository bootstrap: installs Node dependencies, provisions a
# local Postgres database for the lead-capture API routes, writes a default
# .env when one is absent, and syncs the Prisma schema. Safe to run repeatedly
# and to run once at build time to bake the baseline snapshot.
set -euo pipefail

cd "$(dirname "$0")/.."

echo "==> Installing Node dependencies"
npm ci

echo "==> Ensuring Postgres is installed"
if ! command -v pg_ctlcluster >/dev/null 2>&1; then
  sudo apt-get update -qq
  sudo DEBIAN_FRONTEND=noninteractive apt-get install -y -qq postgresql postgresql-contrib
fi

PG_VER="$(ls /usr/lib/postgresql/ | sort -n | tail -1)"
echo "==> Using Postgres ${PG_VER}"

echo "==> Starting Postgres cluster"
sudo pg_ctlcluster "$PG_VER" main start 2>/dev/null || true

echo "==> Waiting for Postgres to accept connections"
for _ in $(seq 1 30); do
  if sudo -u postgres pg_isready -q; then break; fi
  sleep 1
done

echo "==> Ensuring role and database exist"
sudo -u postgres psql -tc "SELECT 1 FROM pg_roles WHERE rolname='golo'" | grep -q 1 \
  || sudo -u postgres psql -c "CREATE ROLE golo WITH LOGIN PASSWORD 'golo';"
sudo -u postgres psql -tc "SELECT 1 FROM pg_database WHERE datname='golo'" | grep -q 1 \
  || sudo -u postgres createdb -O golo golo

if [ ! -f .env ]; then
  echo "==> Writing default .env (local Postgres, SMS + email in stub mode)"
  cat > .env <<'EOF'
# Local Cloud Agent development environment (generated by scripts/cloud-agent-install.sh).
# SMS + email stay blank so both run in safe stub mode. Real secrets set in the
# environment take precedence over these values.
DATABASE_URL="postgresql://golo:golo@127.0.0.1:5432/golo?schema=public"
DIRECT_URL="postgresql://golo:golo@127.0.0.1:5432/golo?schema=public"

SMS_PROVIDER="twilio"
TWILIO_ACCOUNT_SID=""
TWILIO_AUTH_TOKEN=""
TWILIO_FROM_NUMBER=""
SMS_MESSAGE_TEMPLATE="Here's your link to download GoLo: {url}"

RESEND_API_KEY=""
CONTACT_NOTIFY_EMAIL="info@golo.golf"
CONTACT_FROM_EMAIL="GoLo Website <onboarding@resend.dev>"

NEXT_PUBLIC_SITE_URL="http://localhost:3000"
NEXT_PUBLIC_DOWNLOAD_URL="http://localhost:3000/get"
NEXT_PUBLIC_SHOW_STATS="true"
NEXT_PUBLIC_SHOW_TESTIMONIALS="true"
NEXT_PUBLIC_HERO_BACKDROP="sunset"
EOF
fi

echo "==> Syncing Prisma schema to the database"
npm run db:push

echo "==> Install complete"
